### PR TITLE
SONARJNKNS-292 Autopopulate PR values

### PR DESCRIPTION
**Pull request by timja**
Tested using:

https://github.com/hmcts/spring-boot-template/pull/57
https://sonarcloud.io/project/issues?id=uk.gov.hmcts.reform%3Aspring-boot-template&pullRequest=57&resolved=false

image

### CODE REVIEW

**Review by nitinprabhu — APPROVED** [review]
Nice work. Looks good to me . It was quick 💃 🏅

**Comment by timja** [comment]
@henryju Could you take a look please?

**Comment by henryju** [comment]
Can you tell me what is the plugin populating those environment variables?

**Comment by timja** [comment]
I believe its this plugin:
https://github.com/jenkinsci/github-branch-source-plugin
CHANGE_ID is documented here:
https://jenkins.io/doc/book/pipeline/multibranch/

**Comment by henryju** [comment]
Thanks, may I ask you to open a new PR in our official repo: https://github.com/SonarSource/sonar-scanner-jenkins it will be easier for us since we do all our developments there.

**Comment by timja** [comment]
@henryju opened here:
https://github.com/SonarSource/sonar-scanner-jenkins/pull/108

Closing this

**Pull request closed without merging**
